Implement Dimming actuator
kingsleyadam/local-abbfreeathome pull request #48
Opened 2024-10-16 21:40 UTC by derjoerg

This implements the Dimming actuator

2024-10-16 22:03 UTC, derjoerg commented
I don't get it how to test the set_brightness() function

2024-10-17 12:14 UTC, kingsleyadam commented
> This implements the Dimming actuator

Have you been able to run tests locally? That'll help a lot in triaging the tests.

Setup a Python virtual environment and install the PyPi package `pip install .` while in the root directory.

Install Python dev dependencies `pip install src/abbfreeathome/dev-requirements.txt`

Then run the following to run tests.

```
pytest \                                                                                                                                                                                                                                                
  --doctest-modules \
  --junitxml=junit/test-results.xml \
  --cov=abbfreeathome \
  --cov-report=xml:coverage/coverage.xml \
  --cov-report=html:coverage/htmlcov
```
I can get this added to a contribution readme.

2024-10-17 14:06 UTC, derjoerg commented
> > This implements the Dimming actuator
> 
> Have you been able to run tests locally? That'll help a lot in triaging the tests.
> 
> Setup a Python virtual environment and install the PyPi package `pip install .` while in the root directory.
> 
> Install Python dev dependencies `pip install src/abbfreeathome/dev-requirements.txt`
> 
> Then run the following to run tests.
> 
> ```
> pytest \                                                                                                                                                                                                                                                
>   --doctest-modules \
>   --junitxml=junit/test-results.xml \
>   --cov=abbfreeathome \
>   --cov-report=xml:coverage/coverage.xml \
>   --cov-report=html:coverage/htmlcov
> ```
> 
> I can get this added to a contribution readme.

Thanks a lot for the explanation. I've set now everything in visual studio code and it seems to run, but ...
My local pytest displays all tests as passed, but here it shows "failed" again.

2024-10-17 14:14 UTC, derjoerg commented on src/abbfreeathome/devices/dimming_actuator.py
> +            await self.turn_on()
Your are right, this works. I just checked which messages came around on the websocket, when I do this through the legacy freeathome-integration.

2024-10-17 18:18 UTC, kingsleyadam commented
> Thanks a lot for the explanation. I've set now everything in visual studio code and it seems to run, but ... My local pytest displays all tests as passed, but here it shows "failed" again.
> 
> Additionally, I think set_brightness is not fully tested, but I don't undetstand how to use the "dimming_actuator._api.set_datapoint.assert_called_with()" meaningfull as it returns different stuff as it should 😢

Your latest one is failing because of code coverage. You can view the results under the action summary.

https://github.com/kingsleyadam/local-abbfreeathome/actions/runs/11386836788

Once you run the test it'll publish a code coverage HTML output so you can see what still needs to be covered. It should be at: `./coverage/htmlcov/index.html`

<img width="769" alt="Screenshot 2024-10-17 at 20 12 54" src="https://github.com/user-attachments/assets/63dc81ee-e878-446f-bcb7-e0870944cddb">

It's just one line where a device update wouldn't affect the state.

2024-10-17 19:51 UTC, derjoerg commented
> > Thanks a lot for the explanation. I've set now everything in visual studio code and it seems to run, but ... My local pytest displays all tests as passed, but here it shows "failed" again.
> > Additionally, I think set_brightness is not fully tested, but I don't undetstand how to use the "dimming_actuator._api.set_datapoint.assert_called_with()" meaningfull as it returns different stuff as it should 😢
> 
> Your latest one is failing because of code coverage. You can view the results under the action summary.
> 
> https://github.com/kingsleyadam/local-abbfreeathome/actions/runs/11386836788
> 
> Once you run the test it'll publish a code coverage HTML output so you can see what still needs to be covered. It should be at: `./coverage/htmlcov/index.html`
> 
> <img alt="Screenshot 2024-10-17 at 20 12 54" width="769" src="https://private-user-images.githubusercontent.com/5278244/377584691-63dc81ee-e878-446f-bcb7-e0870944cddb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxOTQzMTQsIm5iZiI6MTcyOTE5NDAxNCwicGF0aCI6Ii81Mjc4MjQ0LzM3NzU4NDY5MS02M2RjODFlZS1lODc4LTQ0NmYtYmNiNy1lMDg3MDk0NGNkZGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTdUMTk0MDE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjFlMDhiYmZjNzU3YzkxN2FhZWEzZjYzZTY0NjI1YzkxMjM0ZjhkNjViYTVlNGU1OWVhMjI4YjE4ZGZjYjI2YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.eh_Qiy9Wkzk-EJv4AR3l3mtwIbWtVlRr82AnyOy-XgE">
> It's just one line where a device update wouldn't affect the state.

Sorry, I'm totally lost here. When I run the pytest-command as stated by you above I get a coverage-output stating that everything is OK.
Also, when I look at your hint I don't understand why this line is a problem. It is exactly the same like e.g. in MovementDetector

2024-10-17 20:45 UTC, kingsleyadam commented
> Sorry, I'm totally lost here. When I run the pytest-command as stated by you above I get a coverage-output stating that everything is OK.
> 
> Also, when I look at your hint I don't understand why this line is a problem. It is exactly the same like e.g. in MovementDetector

No worries, I'll take a look tomorrow.

I noticed an issue with how I setup the tests that make it really hard to triage in VS Code. I'll make a change tomorrow which will allow you to see coverage in VS Code and Debug the Test Code including stepping into the module code.

2024-10-18 10:23 UTC, kingsleyadam requested changes
With these adjustments you should get 100% coverage.

```
Name                                             Stmts   Miss  Cover
--------------------------------------------------------------------
src/__init__.py                                      0      0   100%
src/abbfreeathome/__init__.py                        0      0   100%
src/abbfreeathome/api.py                           150      0   100%
src/abbfreeathome/bin/__init__.py                    0      0   100%
src/abbfreeathome/bin/function.py                  403      0   100%
src/abbfreeathome/bin/interface.py                   8      0   100%
src/abbfreeathome/bin/pairing.py                   323      0   100%
src/abbfreeathome/bin/parameter.py                   0      0   100%
src/abbfreeathome/devices/__init__.py                0      0   100%
src/abbfreeathome/devices/base.py                   70      0   100%
src/abbfreeathome/devices/dimming_actuator.py       47      0   100%
src/abbfreeathome/devices/movement_detector.py      29      0   100%
src/abbfreeathome/devices/switch_actuator.py        32      0   100%
src/abbfreeathome/devices/switch_sensor.py          23      0   100%
src/abbfreeathome/devices/trigger.py                14      0   100%
src/abbfreeathome/exceptions.py                     33      0   100%
src/abbfreeathome/freeathome.py                     65      0   100%
--------------------------------------------------------------------
TOTAL                                             1197      0   100%
```

2024-10-18 10:23 UTC, kingsleyadam commented on tests/test_dimming_actuator.py
> +    }
Add an additional output that exists in a dimmer actuator that doesn't affect the state.

```suggestion
       outputs = {
        "odp0000": {"pairingID": 256, "value": "0"},
        "odp0001": {"pairingID": 272, "value": "50"},
        "odp0003": {"pairingID": 257, "value": "0"},
    }
```

2024-10-18 10:23 UTC, kingsleyadam commented on tests/test_dimming_actuator.py
> +    assert dimming_actuator.state is False
Refresh the state from an output that doesn't affect the state.

```suggestion
    # Check output that does NOT affect the state,
    # ensure state, brightness are unchanged.
    dimming_actuator._refresh_state_from_output(
        output={"pairingID": 257, "value": "0"},
    )
    assert dimming_actuator.brightness == 75
    assert dimming_actuator.state is True
```

2024-10-18 10:23 UTC, kingsleyadam commented on tests/test_dimming_actuator.py
> +from abbfreeathome.devices.dimming_actuator import DimmingActuator
Reference module files directly (vs installed module)

```suggestion
from src.abbfreeathome.api import FreeAtHomeApi
from src.abbfreeathome.devices.dimming_actuator import DimmingActuator
```

2024-10-18 12:57 UTC, kingsleyadam approved these changes

2024-10-18 12:57 UTC, merged